- name: "Instalar Apache2 y mysql_client"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - mariadb-client

- name: "Crear el virtualhost"
  template:
    src: /etc/apache2/sites-available/pepepracticaansible.conf  
    dest: /etc/apache2/sites-available/pepepracticaansible.conf 
    owner: root
    group: root
    mode: '0644'

- name: "Activar el virtualhost"
  file:
    src: /etc/apache2/sites-available/pepepracticaansible.conf 
    dest: /etc/apache2/sites-enabled/pepepracticaansible.conf 
    state: link

- name: "Crear un directorio (file, status: directory)"
  file:
    path: /var/www/html  
    state: directory

- name: "Activar el módulo rewriter (apache2_modules)"
  apache2_module:
    name: rewrite
    state: present

- name: "Copiar index.html"
  copy:
    src: /var/www/html/index.html  
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: "Añadir una resolución estática"
  command: "echo '192.168.1.2 www.pepepracticaansible.com' >> /etc/hosts" 

- name: "Copiar fichero de configuración y reiniciar el servicio"
  copy:
    src: /etc/apache2/ports.conf
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart apache2