- name: "ensure apache2 is installed"
  apt:
    pkg: apache2

- name: cambiar la ruta por defecto
  shell: ip route delete default && ip route add default via 192.168.1.1 && echo "post-up route add -net 192.168.1.0 netmask 255.255.255.0 gw 192.168.1.0 dev eth1" >> /etc/network/interfaces

- name: copy template index
  template:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: 0644

- name: "Copiar fichero al servidor remoto"
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: "Copiar fichero de configuración y reiniciar el servicio"
  copy:
    src: etc/apache2/ports.conf
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart apache2
