- hosts: redinterna
  become: true
  roles:
   - role: redinterna

- hosts: router
  become: true
  roles:
   - role: router

- hosts: all
  become: true
  roles:
   - role: common

- hosts: web
  become: true
  roles:
   - role: web

- hosts: bd
  become: true
  roles:
   - role: bd
